PROGRAM SPECGEN_MAIN
    !#################################################################################
    !#SPECGEN CALCULATES THE FOLLOWING DATA:                                         #
    !#      -TUBE SPECTRUM                                                           #
    !#      -SECONDARY TARGET SPECTRUM                                               #
    !#      -INTENSITY OF CHARACTERISTIC LINES OF A SAMPLE                           #
    !#                                                                               #
    !#CHRISTOPHER GEERLINGS 07/04/2015                                               #
    !#################################################################################
    USE     :: ISO_FORTRAN_ENV
    USE     :: xraylib
    USE     :: XRLDATA
    USE     :: CFGDATA
    USE     :: ANODE
    USE     :: CONSTANTS
    USE     :: SECCOMP
    USE     :: MICROMATTER

    IMPLICIT NONE
    INTEGER :: CNT, N, CNT2, NELEMENT
    CHARACTER(LEN=16)   :: ARG0
    REAL(16) :: EI, I, K, EC, EA
    REAL(16)    :: KAPPA, PI
    REAL(16)    :: ISAM1, ISAM2

    PI = 2.D0*DASIN(1.D0)

    OPEN(UNIT=999, FILE='DEBUG.LOG', ACCESS='APPEND', STATUS='REPLACE')
    OPEN(UNIT=100, STATUS='SCRATCH')    !BUFFER

    OPEN(UNIT=101, STATUS='SCRATCH')    !ANODE CONTINUUM
    OPEN(UNIT=102, STATUS='SCRATCH')    !ANODE CHARACTERISTIC LINES
    OPEN(UNIT=103, STATUS='SCRATCH')    !TUBE SPECTRUM
    OPEN(UNIT=111, STATUS='SCRATCH')    !SECONDARY TARGET CONTINUUM
    OPEN(UNIT=112, STATUS='SCRATCH')    !SECONDARY TARGET CHARACTERISTIC LINES
    OPEN(UNIT=113, STATUS='SCRATCH')    !SECONDARY TARGET SPECTRUM
    OPEN(UNIT=131, STATUS='SCRATCH')    !SAMPLE CHARACTERISTIC LINES

    OPEN(UNIT=121,FILE='OUTPUT.DAT', ACCESS='APPEND', STATUS='REPLACE')

    !SET UP CONFIG-FILES
    CALL INITCFG()
    !READ SELECTOR FROM COMMAND LINE
    !   = 0 THEN LOAD CONFIG FROM FILES AND DISPLAY MENU
    !   = 1 THEN READ PARAMETERS FROM COMMAND LINE
    CALL GET_COMMAND_ARGUMENT(1, ARG0)
    ARG0 = ADJUSTL(ARG0)
    READ(ARG0,'(I1)') CNT
    IF (CNT.EQ. 0) THEN
        CALL LOADCFG()
    ELSEIF (CNT.EQ. 1) THEN
        CALL READCFG()
    ENDIF

    CALL DEBUGCFG()

    !CALCULATE A VALUE FOR THE PROPORTIONAL CONSTANT KAPPA
    WRITE (6,*) 'CALCULATING KAPPA'
    KAPPA = CHECKKAPPA(32._16)

    !WRITING LIST OF ENERGY VALUES IN CONTINUUM
    WRITE (6,*) 'INITIALIZING ENERGY VALUES'
    DO CNT = 1, NSTEP
        WRITE (6,'(I4,1H/,I4,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
        WRITE (100,200) (EMIN + ESTEP*DBLE(CNT))
    END DO

    !CALCULATING INTENSITY OF CONTINUUM OF X-RAY TUBE
!    WRITE (6,*) 'CALCULATING INTENSITY OF CONTINUUM OF X-RAY TUBE'
!    REWIND(100)
!    DO CNT = 1, NSTEP
!        WRITE (6,'(I4,1H/,I4,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
!        READ (100,200) EI
!        WRITE (101,201) EI, ANODECONT(EI)
!    END DO
!    REWIND(100)

    !CALCULATING INTENSITIES OF CHARACTERISTIC LINES OF ANODE
!    WRITE (6,*) 'CALCULATING INTENSITIES OF CHARACTERISTIC LINES OF ANODE'
!    DO N = 1, SIZE(LINE)
!        WRITE (6,'(I3,1H/,I3,A1,$)',ADVANCE='NO') N, SIZE(LINE), CHAR(13)
!        EI = LineEnergy(Z_ANODE, LINE(N))
!        WRITE (102,201) EI, ANODECHAR(N, KAPPA)
!    END DO

    !CALCULATING TUBE SPECTRUM USING ENERGY VALUES CALCULATED EARLIER
    !IF THERE IS CHARACTERISTIC LINE AT THAT POSITION, ADD SPACING OF
    !ESTEP/10 BEFORE AND AFTER CHARACTERISTIC LINE WITH THE INTENSITY
    !OF THE CONTINUUM. THEN PLOT A POINT WITH THE INTENSITY OF THE
    !CHARACTERISTIC LINE I NBETWEEN.
    !IF THERE IS NO CHARACTERISTIC LINE AT THAT POSITION,
    !PLOT INTENSITY OF CONTINUUM.
!    WRITE (6,*) 'CALCULATING TUBE SPECTRUM'
!    DO CNT = 1, NSTEP
!        READ (100,200) EI
!        DO N = 1, SIZE(LINE)
!            WRITE (6,'(I4,1H/,I4,3H-->,I3,1H/,I3,A1,$)',ADVANCE='NO'), CNT, NSTEP, N, SIZE(LINE), CHAR(13)
!            EA = LineEnergy(Z_ANODE, LINE(N))
!            IF (EA.EQ.0) CYCLE
!            K = ANINT(EA/ESTEP)*ESTEP
!            IF (K.EQ. EI) THEN
!                EC = LineEnergy(Z_ANODE, LINE(N))
!                WRITE (103,201) EC-(ESTEP/10), ANODECONT(EC-(ESTEP/10))
!                WRITE (103,201) EC, ANODECHAR(N, KAPPA)
!                WRITE (103,201) EC+(ESTEP/10), ANODECONT(EC+(ESTEP/10))
!                CYCLE
!            ENDIF
!        END DO
!        WRITE (103,201) EI, ANODECONT(EI)
!    END DO

    !CALCULATING INTENSITY OF SCATTERED CONTINUUM OF X-RAY TUBE
!    WRITE (6,*) 'CALCULATING INTENSITY OF SCATTERED CONTINUUM OF X-RAY TUBE'
!    REWIND(100)
!    DO CNT = 1,NSTEP
!        WRITE (6,'(I5,1H/,I5,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
!        READ (100,200) EI
!        WRITE (111,201) EI, SECTCONT(EI)
!    END DO

    !CALCULATING INTENSITIES OF CHARACTERISTIC LINES
!    WRITE (6,*) 'CALCULATING INTENSITIES OF CHARACTERISTIC LINES'
!    DO CNT = 1, SIZE(LINE)
!        DO N = 1, CP_ST%NELEMENTS
!            WRITE (6,'(I3,1H/,I3,A1,$)',ADVANCE='NO') CNT, SIZE(LINE), CHAR(13)
!            EI = LineEnergy(CP_ST%ELEMENTS(N), LINE(CNT))
!            IF (EI.EQ.0) CYCLE
!            WRITE (112,201) EI, SECCOMPCHAR(CNT, CP_ST%ELEMENTS(N), KAPPA)
!        END DO
!    END DO

    !CALCULATING SECONDARY TARGET SPECTRUM USING ENERGY VALUES
    !CALCULATED EARLIER. IF THERE IS CHARACTERISTIC LINE AT THAT
    !POSITION, ADD SPACING OF ESTEP/10 BEFORE AND AFTER
    !CHARACTERISTIC LINE WITH THE INTENSITY OF THE SCATTERED
    !CONTINUUM. THEN PLOT A POINT WITH THE INTENSITY OF THE
    !CHARACTERISTIC LINE I NBETWEEN.
    !IF THERE IS NO CHARACTERISTIC LINE AT THAT POSITION,
    !PLOT INTENSITY OF SCATTERED CONTINUUM.
    !THIS IS REPEATED FOR THE SCATTERED CHARACTERISTIC LINES
    !OF THE ANODE (BOTH RAYLEIGH AND COMPTON SCATTERED).
!    WRITE (6,*) 'CALCULATING SECONDARY TARGET SPECTRUM'
!    REWIND(100)
!    DO CNT = 1, NSTEP
!        READ (100,200) EI
!        DO N = 1, SIZE(LINE)
!            WRITE (6,'(I4,1H/,I4,3H-->,I3,1H/,I3,A1,$)',ADVANCE='NO'), CNT, NSTEP, N, SIZE(LINE), CHAR(13)
!            EA = LineEnergy(Z_ANODE, LINE(N))
!            IF (EA.EQ.0) CYCLE
!            K = ANINT(EA/ESTEP)*ESTEP
!            IF (K.EQ. EI) THEN
!                EC = EA
!                WRITE (104,201) EC-(ESTEP/10), SECTCONT(EC-(ESTEP/10))
!                WRITE (104,201) EC, SECTRAYL(KAPPA, N)
!                WRITE (104,201) EC+(ESTEP/10), SECTCONT(EC+(ESTEP/10))
!                CYCLE
!            ENDIF
!            K = ANINT(ComptonEnergy(DBLE(EA), DBLE((PI/2)-A_ST_AZIM_OUT))/ESTEP)*ESTEP
!            IF (K.EQ. EI) THEN
!                EC = ComptonEnergy(LineEnergy(Z_ANODE, LINE(N)), DBLE((PI/2)-A_ST_AZIM_OUT))
!                WRITE (104,201) EC-(ESTEP/10), SECTCONT(EC-(ESTEP/10))
!                WRITE (104,201) EC, SECTCOMP(KAPPA, N)
!                WRITE (104,201) EC+(ESTEP/10), SECTCONT(EC+(ESTEP/10))
!                CYCLE
!            ENDIF
!            DO CNT2 = 1, CP_ST%NELEMENTS
!                EC = LineEnergy(CP_ST%ELEMENTS(CNT2), LINE(N))
!                IF (EC.EQ.0) CYCLE
!                K = ANINT(EC/ESTEP)*ESTEP
!                IF (K.EQ. EI) THEN
!                    WRITE (104,201) EC-(ESTEP/10), SECTCONT(EC-(ESTEP/10))
!                    WRITE (104,201) EC, SECCOMPCHAR(N, CP_ST%ELEMENTS(CNT2),KAPPA)
!                    WRITE (104,201) EC+(ESTEP/10), SECTCONT(EC+(ESTEP/10))
!                    CYCLE
!                ENDIF
!            END DO
!        END DO
!        WRITE (104,201) EI, SECTCONT(EI)
!    END DO
    DO CNT2 = 1, CP_SAM%NELEMENTS
    DO CNT = 1, SIZE(LINE)
    IF (LineEnergy(CP_SAM%ELEMENTS(CNT2), LINE(CNT)).EQ. 0) CYCLE
    IF (LineEnergy(CP_SAM%ELEMENTS(CNT2), LINE(CNT)).LE. EMIN) CYCLE
    write (6,*) LineEnergy(CP_SAM%ELEMENTS(CNT2), LINE(CNT))
    WRITE (6,'(I3,1H/,I3,A1,$)',ADVANCE='NO') CNT, SIZE(LINE), CHAR(13)
    NELEMENT = CP_SAM%ELEMENTS(CNT2)
    ISAM1 = MM1(CNT, NELEMENT, KAPPA)
    ISAM1 = ISAM1 + MM2(CNT, NELEMENT, KAPPA)
    ISAM1 = ISAM1 + MM3(CNT, NELEMENT, KAPPA)
    !ISAM1 = ISAM1*EXP(-MAC(Z_WINDOW, EI)*0.008)
!
     ISAM2 = MM1(CNT, NELEMENT, KAPPA)
    ISAM2 = ISAM2 + MM2(CNT, NELEMENT, KAPPA)
    ISAM2 = ISAM2 + MM3(CNT, NELEMENT, KAPPA)

    WRITE (131,202) LineEnergy(NELEMENT, LINE(CNT)), CONC, ISAM1, ISAM2
    END DO
    END DO
    !WRITING OUTPUT TO FILE
    WRITE (6,*) 'WRITING OUTPUT TO FILE'
    REWIND(131)
    DO
        READ (131,202,END=999) EI, CONC, ISAM1, ISAM2
        WRITE (121,202) EI, CONC, ISAM1, ISAM2
    END DO
200 FORMAT(ES32.20E3)
201 FORMAT(ES32.20E3, 2X, ES32.20E4)
202 FORMAT(ES32.20E3, 2X, 3ES32.20E4)
999 CLOSE(100)
    CLOSE(101)
    CLOSE(102)
    CLOSE(111)
    CLOSE(112)
    CLOSE(121)
    CLOSE(131)
    CLOSE(999)
END PROGRAM SPECGEN_MAIN
