MODULE CONVOLUTE
    USE :: xraylib
    USE :: CFGDATA
    USE :: XRLDATA
    implicit none
CONTAINS
    FUNCTION GAUSS(EI, G_ARRAY)
        IMPLICIT NONE
        REAL(8) :: GAUSS
        REAL(8) :: EI
        REAL(8) :: GAIN, ZERO, FANO, ETA, NOISE, CENTER
        REAL(8) :: FWHM
        REAL(8) :: SIGMA
        REAL(8), DIMENSION(3)   :: G_ARRAY !HEIGHT, WIDTH, CENTER
        REAL(8) :: PI
        PI = 2.D0*DASIN(1.D0)

        DATA FANO/0.105050176382065/
        DATA NOISE/8.76991301774979E-02/
        DATA ZERO/-5.59411989524961E-03/
        DATA ETA/3.86/

        CENTER = G_ARRAY(3)*1E3
        GAIN = ZERO + ESTEP*1E3

        FWHM = SQRT((NOISE**2)+(8*LOG10(2.)*ETA*CENTER*FANO))
        SIGMA = FWHM/(2*SQRT(2*LOG10(2.)))
        GAUSS = (GAIN/(SIGMA*SQRT(2*PI)))*EXP(-0.5*((EI*1E3-CENTER)/SIGMA)**2)
    END FUNCTION GAUSS
    SUBROUTINE CONVOLUTE_SPEC()
        USE :: CFGDATA
        USE :: XRLDATA
        IMPLICIT NONE
        INTEGER :: NCHAR, NCONT, CNT, CNT2
        REAL(8) :: ITMP, EI, E
        REAL(8), DIMENSION(3)   :: G_ARRAY !HEIGHT, WIDTH, CENTER
        REAL(8), DIMENSION(:), ALLOCATABLE  :: I_ARRAY
        REAL(8), DIMENSION(:), ALLOCATABLE  :: I_CONV_ARRAY
        REAL(8), DIMENSION(:), ALLOCATABLE  :: E_ARRAY

        DATA NCHAR/0/
        DATA NCONT/0/

        REWIND(4)
        REWIND(8)
        OPEN(UNIT=7,FILE='OUTPUT.CNV',STATUS='REPLACE')
        OPEN(UNIT=99,STATUS='SCRATCH')

        DO
            READ (104,200,END=2) EI, ITMP
            NCONT = NCONT + 1
        END DO
2       CONTINUE
        ALLOCATE(I_ARRAY(NCONT))
        ALLOCATE(I_CONV_ARRAY(NCONT))
        ALLOCATE(E_ARRAY(NCONT))
        I_ARRAY = 0._8
        REWIND(104)
        DO CNT = 1, NCONT
            READ (104,200,END=3) E_ARRAY(CNT), I_ARRAY(CNT)
        END DO
3   CONTINUE
    REWIND(112)
    DO CNT = 1, NCONT
        G_ARRAY(3) = E_ARRAY(CNT)
        G_ARRAY(1) = I_ARRAY(CNT)
        E = DBLE(CNT)*ESTEP
        DO CNT2 = 1, NCONT
            I_CONV_ARRAY(CNT) = I_CONV_ARRAY(CNT) + GAUSS(E_ARRAY(CNT)*1E3, G_ARRAY)*G_ARRAY(1)
        END DO
    END DO
    DO CNT = 1, NCONT
        WRITE (7,200) E_ARRAY(CNT), I_CONV_ARRAY(CNT)
    END DO
200 FORMAT(ES32.20E3, 2X, ES32.20E4)
        CLOSE(7)
        RETURN
    END SUBROUTINE CONVOLUTE_SPEC
END MODULE CONVOLUTE
