MODULE CONVOLUTE
    USE :: xraylib
    USE :: TYPES
    USE :: CFGDATA
    USE :: XRLDATA
    implicit none
CONTAINS
    FUNCTION GAUSS(EI, G_ARRAY)
        IMPLICIT NONE
        REAL(QP) :: GAUSS
        REAL(DP) :: EI
        REAL(QP) :: GAIN, ZERO, FANO, ETA, NOISE, CENTER
        REAL(QP) :: FWHM
        REAL(QP) :: SIGMA
        REAL(QP), DIMENSION(3)   :: G_ARRAY !HEIGHT, WIDTH, CENTER
        REAL(QP) :: PI
        REAL(QP)    :: CON
        REAL(QP)    :: CON2 = 2_QP
        PI = 2.D0*DASIN(1.D0)

        DATA FANO/0.105050176382065/
        DATA NOISE/8.76991301774979E-02/
        DATA ZERO/0/
        DATA ETA/3.86/

        CON = 2*SQRT(2*LOG(CON2))
        CENTER = G_ARRAY(3)
        GAIN = ZERO + ESTEP*(1E3)

        FWHM = SQRT((NOISE**2)+(CON**2)*ETA*CENTER*(1E3)*FANO)
        SIGMA = FWHM/CON/(1E3)
        GAUSS = (GAIN/(SIGMA*SQRT(2*PI)))*EXP(-0.5*((EI-CENTER)/SIGMA)**2)
        RETURN
    END FUNCTION GAUSS
    SUBROUTINE CONVOLUTE_SPEC(NFILE)
        USE :: CFGDATA
        USE :: XRLDATA
        IMPLICIT NONE
        INTEGER :: NCHAR, NCONT, CNT, CNT2
        INTEGER :: NFILE
        REAL(QP) :: ITMP, EI, E
        REAL(QP), DIMENSION(3)   :: G_ARRAY !HEIGHT, WIDTH, CENTER
        REAL(QP), DIMENSION(:), ALLOCATABLE  :: I_ARRAY
        REAL(QP), DIMENSION(:), ALLOCATABLE  :: I_CONV_ARRAY
        REAL(DP), DIMENSION(:), ALLOCATABLE  :: E_ARRAY

        DATA NCHAR/0/
        DATA NCONT/0/

        REWIND(4)
        REWIND(8)
        OPEN(UNIT=7,FILE='OUTPUT.CNV',STATUS='REPLACE')
        OPEN(UNIT=99,STATUS='SCRATCH')

        DO
            READ (NFILE,200,END=2) EI, ITMP
            NCONT = NCONT + 1
        END DO
2       CONTINUE
        ALLOCATE(I_ARRAY(NCONT))
        ALLOCATE(I_CONV_ARRAY(NCONT))
        ALLOCATE(E_ARRAY(NCONT))
        I_ARRAY = 0._QP
        REWIND(NFILE)
        DO CNT = 1, NCONT
            READ (NFILE,200,END=3) E_ARRAY(CNT), I_ARRAY(CNT)
        END DO
3   CONTINUE
    DO CNT = 1, NCONT
        G_ARRAY(3) = E_ARRAY(CNT)
        G_ARRAY(1) = I_ARRAY(CNT)
        E = DBLE(CNT)*ESTEP
        DO CNT2 = 1, NCONT
            I_CONV_ARRAY(CNT2) = I_CONV_ARRAY(CNT2) + GAUSS(E_ARRAY(CNT2), G_ARRAY)*G_ARRAY(1)
            !WRITE (6,*) GAUSS(E_ARRAY(CNT2)*1E3, G_ARRAY)
        END DO
    END DO
    DO CNT = 1, NCONT
        WRITE (7,200) E_ARRAY(CNT), I_CONV_ARRAY(CNT)
    END DO
200 FORMAT(ES32.20E3, 2X, ES32.20E4, 2X)
        CLOSE(7)
        RETURN
    END SUBROUTINE CONVOLUTE_SPEC
END MODULE CONVOLUTE
