MODULE TYPES
    IMPLICIT NONE
    INTEGER, PARAMETER ::   WP = SELECTED_REAL_KIND(P=30)
    INTEGER, PARAMETER ::   QP = SELECTED_REAL_KIND(P=30)
    INTEGER, PARAMETER ::   DP = SELECTED_REAL_KIND(P=15)
END MODULE TYPES
