PROGRAM MMSENS
    USE     :: ISO_FORTRAN_ENV
    USE     :: xraylib
    USE     :: TYPES
    USE     :: XRLDATA
    USE     :: CFGDATA
    USE     :: ANODE
    USE     :: CONSTANTS
    USE     :: SECCOMP
    USE     :: MICROMATTER

    IMPLICIT NONE
    INTEGER :: CNT
    CHARACTER(LEN=16)   :: ARG0
    REAL(DP)    :: EI = 0_DP
    REAL(QP)    :: ITMP = 0_DP

    OPEN(UNIT=121,FILE='OUTPUT_DE.DAT', ACCESS='APPEND', STATUS='REPLACE')

    !SET UP CONFIG-FILES
    CALL INITCFG()
    !READ SELECTOR FROM COMMAND LINE
    !   = 0 THEN LOAD CONFIG FROM FILES AND DISPLAY MENU
    !   = 1 THEN READ PARAMETERS FROM COMMAND LINE
    CALL GET_COMMAND_ARGUMENT(1, ARG0)
    ARG0 = ADJUSTL(ARG0)
    READ(ARG0,'(I1)') CNT
    IF (CNT.EQ. 0) THEN
        CALL LOADCFG()
    ELSEIF (CNT.EQ. 1) THEN
        CALL READCFG()
    ENDIF

    CALL DEBUGCFG()
    CALL DISPCFG()

    DO CNT = 1, NSTEP
        EI = EMIN + ESTEP*DBLE(CNT)
        ITMP = DETEFF(EI)
        WRITE (121,201) EI, ITMP
    END DO
201 FORMAT(ES32.20E3, 2X, ES32.20E4)
    CLOSE(121)
END PROGRAM MMSENS
