PROGRAM TSPEC
    USE :: xraylib
    USE     :: ISO_FORTRAN_ENV
    USE     :: xraylib
    USE     :: XRLDATA
    USE     :: CFGDATA
    USE     :: ANODE
    USE     :: CONSTANTS

    IMPLICIT NONE
    INTEGER :: CNT, N, CNT2, NELEMENT
    CHARACTER(LEN=16)   :: ARG0
    REAL(16) :: EI, I, K, EC, EA
    REAL(16)    :: KAPPA, PI
    REAL(16)    :: ISAM1, ISAM2
    REAL        :: START, FINISH

    PI = 2.D0*DASIN(1.D0)

    OPEN(UNIT=999, FILE='DEBUG.LOG', ACCESS='APPEND', STATUS='REPLACE')
    OPEN(UNIT=100, STATUS='SCRATCH')    !BUFFER

    OPEN(UNIT=101, STATUS='SCRATCH')    !ANODE CONTINUUM
    OPEN(UNIT=102, STATUS='SCRATCH')    !ANODE CHARACTERISTIC LINES
    OPEN(UNIT=103, STATUS='SCRATCH')    !TUBE SPECTRUM

    OPEN(UNIT=121,FILE='OUTPUT.DAT', ACCESS='APPEND', STATUS='REPLACE')

        !SET UP CONFIG-FILES
    CALL INITCFG()
    !READ SELECTOR FROM COMMAND LINE
    !   = 0 THEN LOAD CONFIG FROM FILES AND DISPLAY MENU
    !   = 1 THEN READ PARAMETERS FROM COMMAND LINE
    CALL GET_COMMAND_ARGUMENT(1, ARG0)
    ARG0 = ADJUSTL(ARG0)
    READ(ARG0,'(I1)') CNT
    IF (CNT.EQ. 0) THEN
        CALL LOADCFG()
    ELSEIF (CNT.EQ. 1) THEN
        CALL READCFG()
    ENDIF

    CALL DEBUGCFG()
    CALL DISPCFG()

    !WRITING LIST OF ENERGY VALUES IN CONTINUUM
    WRITE (6,*) 'INITIALIZING ENERGY VALUES'
    DO CNT = 1, NSTEP
        WRITE (6,'(I4,1H/,I4,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
        WRITE (100,200) (EMIN + ESTEP*DBLE(CNT))
    END DO
    REWIND(100)

    !CALCULATING INTENSITY OF CONTINUUM OF X-RAY TUBE
    WRITE (6,*) 'CALCULATING INTENSITY OF CONTINUUM OF X-RAY TUBE'
    REWIND(100)
    DO CNT = 1, NSTEP
        WRITE (6,'(I4,1H/,I4,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
        READ (100,200) EI
        WRITE (101,201) EI, ANODECONT(EI)
    END DO
    REWIND(100)

    !CALCULATING INTENSITIES OF CHARACTERISTIC LINES OF ANODE
    WRITE (6,*) 'CALCULATING INTENSITIES OF CHARACTERISTIC LINES OF ANODE'
    DO N = 1, SIZE(LINE)
        WRITE (6,'(I3,1H/,I3,A1,$)',ADVANCE='NO') N, SIZE(LINE), CHAR(13)
        EI = LineEnergy(Z_ANODE, LINE(N))
        WRITE (102,201) EI, ANODECHAR(N, KAPPA)
    END DO

    !CALCULATING TUBE SPECTRUM USING ENERGY VALUES CALCULATED EARLIER
    !IF THERE IS CHARACTERISTIC LINE AT THAT POSITION, ADD SPACING OF
    !ESTEP/10 BEFORE AND AFTER CHARACTERISTIC LINE WITH THE INTENSITY
    !OF THE CONTINUUM. THEN PLOT A POINT WITH THE INTENSITY OF THE
    !CHARACTERISTIC LINE I NBETWEEN.
    !IF THERE IS NO CHARACTERISTIC LINE AT THAT POSITION,
    !PLOT INTENSITY OF CONTINUUM.
    WRITE (6,*) 'CALCULATING TUBE SPECTRUM'
    DO CNT = 1, NSTEP
        READ (100,200) EI
        DO N = 1, SIZE(LINE)
            WRITE (6,'(I9,1H/,I9,3H-->,I9,1H/,I9,A1,$)',ADVANCE='NO'), CNT, NSTEP, N, SIZE(LINE), CHAR(13)
            EA = LineEnergy(Z_ANODE, LINE(N))
            IF (EA.EQ.0) CYCLE
            K = ANINT(EA/ESTEP)*ESTEP
            IF (K.EQ. EI) THEN
                EC = LineEnergy(Z_ANODE, LINE(N))
                WRITE (103,201) EC-(ESTEP/10), ANODECONT(EC-(ESTEP/100))
                WRITE (103,201) EC, ANODECONT(EC) + ANODECHAR(N, KAPPA)
                WRITE (103,201) EC+(ESTEP/10), ANODECONT(EC+(ESTEP/100))
                CYCLE
            ENDIF
        END DO
        WRITE (103,201) EI, ANODECONT(EI)
    END DO

        WRITE (6,*) 'WRITING OUTPUT TO FILE'
    REWIND(103)
    DO
        READ (103,201,END=999) EI, I
        WRITE (121,201) EI, I
    END DO
200 FORMAT(ES32.20E3)
201 FORMAT(ES32.20E3, 2X, ES32.20E4)
202 FORMAT(I3, I3, ES32.20E3, 2X, 2ES32.20E4)
999 CLOSE(100)
    CLOSE(101)
    CLOSE(102)
    CLOSE(103)
    CLOSE(999)
END PROGRAM TSPEC
