PROGRAM TSPEC
    !#################################################################################
    !#TSPEC CALCULATES THE SPECTRUM AS EMITTED BY A USER-DEFINED X-RAY TUBE          #
    !#                                                                               #
    !#CHRISTOPHER GEERLINGS 15/04/2015                                               #
    !#################################################################################
    USE     :: xraylib
    USE     :: TYPES
    USE     :: ISO_FORTRAN_ENV
    USE     :: xraylib
    USE     :: XRLDATA
    USE     :: CFGDATA
    USE     :: ANODE

    IMPLICIT NONE
    INTEGER:: CNT
    INTEGER:: N
    CHARACTER(LEN=16):: ARG0
    REAL(DP):: EI = 0_DP
    REAL(QP):: ITMP = 0_QP
    REAL(DP):: EA = 0_DP
    REAL(QP):: PI = 0_QP


    PI = 2.D0*DASIN(1.D0)

    OPEN(UNIT=999, FILE='DEBUG.LOG', ACCESS='APPEND', STATUS='REPLACE')
    OPEN(UNIT=100, STATUS='SCRATCH')    !BUFFER
    OPEN(UNIT=101, STATUS='SCRATCH')    !ANODE CONTINUUM
    OPEN(UNIT=102, STATUS='SCRATCH')    !ANODE CHARACTERISTIC LINES
    OPEN(UNIT=103, STATUS='SCRATCH')    !TUBE SPECTRUM
    OPEN(UNIT=121,FILE='OUTPUT_T.DAT', ACCESS='APPEND', STATUS='REPLACE')

    !SET UP CONFIG-FILES
    CALL INITCFG()
    !READ SELECTOR FROM COMMAND LINE
    !   = 0 THEN LOAD CONFIG FROM FILES AND DISPLAY MENU
    !   = 1 THEN READ PARAMETERS FROM COMMAND LINE
    CALL GET_COMMAND_ARGUMENT(1, ARG0)
    ARG0 = ADJUSTL(ARG0)
    READ(ARG0,'(I1)') CNT
    IF (CNT.EQ. 0) THEN
        CALL LOADCFG()
    ELSEIF (CNT.EQ. 1) THEN
        CALL READCFG()
    ENDIF

!    CALL DEBUGCFG()
    CALL DISPCFG()
    CALL LOAD_NIST()
    !WRITING LIST OF ENERGY VALUES IN CONTINUUM
    WRITE (6,*) 'INITIALIZING ENERGY VALUES'
    DO CNT = 1, NSTEP
        WRITE (6,'(I4,1H/,I4,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
        WRITE (100,200) (EMIN + ESTEP*DBLE(CNT))
    END DO
    REWIND(100)
!
!    !CALCULATING INTENSITY OF CONTINUUM OF X-RAY TUBE
!    WRITE (6,*) 'CALCULATING INTENSITY OF CONTINUUM OF X-RAY TUBE'
!    REWIND(100)
!    DO CNT = 1, NSTEP
!        WRITE (6,'(I4,1H/,I4,A1,$)',ADVANCE='NO') CNT, NSTEP, CHAR(13)
!        READ (100,200) EI
!        WRITE (101,201) EI, ANODE_CONT(EI)
!    END DO
!    REWIND(100)

    !CALCULATING INTENSITIES OF CHARACTERISTIC LINES OF ANODE
    !WRITE (6,*) 'CALCULATING INTENSITIES OF CHARACTERISTIC LINES OF ANODE'
    !DO N = 1, SIZE(LINE)
    !    WRITE (6,'(I3,1H/,I3,A1,$)',ADVANCE='NO') N, SIZE(LINE), CHAR(13)
    !    EI = LineEnergy(Z_ANODE, LINE(N))
    !    WRITE (102,201) EI, ANODE_CHAR(N, Z_ANODE)
    !END DO

    !CALCULATING TUBE SPECTRUM USING ENERGY VALUES CALCULATED EARLIER
    !IF THERE IS CHARACTERISTIC LINE AT THAT POSITION, ADD SPACING OF
    !ESTEP/10 BEFORE AND AFTER CHARACTERISTIC LINE WITH THE INTENSITY
    !OF THE CONTINUUM. THEN PLOT A POINT WITH THE INTENSITY OF THE
    !CHARACTERISTIC LINE I NBETWEEN.
    !IF THERE IS NO CHARACTERISTIC LINE AT THAT POSITION,
    !PLOT INTENSITY OF CONTINUUM.
    WRITE (6,*) 'CALCULATING TUBE SPECTRUM'
    DO CNT = 1, NSTEP
        READ (100,200) EI
        ITMP = ANODE_CONT(Z_ANODE, EI)
        DO N = 1, SIZE(LINE)
            WRITE (6,'(I9,1H/,I9,3H-->,I9,1H/,I9,A1,$)',ADVANCE='NO'), CNT, NSTEP, N, SIZE(LINE), CHAR(13)
            EA = LineEnergy(Z_ANODE, LINE(N))
            IF (EA.EQ.0 .OR. EA.LT.EMIN) CYCLE
            IF (EA.GE.EI .AND. EA.LT.(EI+ESTEP)) THEN
                ITMP = ITMP + ANODE_CHAR(Z_ANODE, N)
            ENDIF
        END DO
        ITMP = ITMP*TUBE_ATTEN(EI, Z_WINDOW, D_WINDOW)*FILTER_ATTEN(EI, Z_FILTER, D_FILTER)
        WRITE (103,201) EI, ITMP
        IF (ISNAN(ITMP)) THEN
            WRITE (6,*) 'ERROR:', EI, ITMP
        ENDIF
    END DO

    WRITE (6,*) 'WRITING OUTPUT TO FILE'
    REWIND(103)
    DO
        READ (103,201,END=999) EI, ITMP
        WRITE (121,201) EI, ITMP
    END DO
200 FORMAT(ES32.20E3)
201 FORMAT(ES32.20E3, 2X, ES32.20E4, 2X)
999 CLOSE(100)
    CLOSE(101)
    CLOSE(102)
    CLOSE(103)
    CLOSE(999)
END PROGRAM TSPEC
